spring:
    datasource:
        url: jdbc:mysql://awseb-e-k9d3ahmgjq-stack-awsebrdsdatabase-nqsvkyedka24.c2qdbstj9o1e.ap-northeast-2.rds.amazonaws.com:3306/board?useSSL=false&serverTimezone=Asia/Seoul
        username: omuu
        password: eodud4976!
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
